# include everything in this directory. 
includeDir = ['.','../Confusion','../DPGTests','../Poisson','../Stokes']

import os
env = Environment(ENV=os.environ,CXX='mpicxx',CC='mpicc',CXXFLAGS = ['-O3','-w'],CPPPATH=includeDir)
#env = Environment(ENV=os.environ,CXX='mpicxx',CC='mpicc',CXXFLAGS = ['-O0','-g'],CPPPATH=includeDir)

# run the Camellia library builder if it's not built already
SConscript('../../build/SConscript',exports = 'env')

# run current SCons script to build driver program
SConscript('SConscript', exports=['env'])
