Import('*')

src_obj = env.Object(['ConfusionBilinearForm.cpp','../Confusion/PenaltyMethodFilter.cpp','ConfectionManufacturedSolution.cpp','BurgersBilinearForm.cpp'])

env.Program('exec/Burgers',['BurgersDriver.cpp',src_obj])
