Import('*')

driver1 = env.Program('exec/Step', ['Confusion_step.cpp'])
driver2 = env.Program('exec/Hughes', ['Confusion_Hughes.cpp'])
driver3 = env.Program('exec/Vortex', ['Vortex.cpp'])
driver4 = env.Program('exec/Rates', ['Rates.cpp'])
driver5 = env.Program('exec/SimpleTest', ['SimpleTest.cpp'])
driver6 = env.Program('exec/Qopt', ['QoptInflowTest.cpp'])
driver7 = env.Program('exec/Time', ['TransientTest.cpp'])

#Default(driver1)
#Default(driver2)
#Default(driver3)
Default(driver4)
Default(driver5)
Default(driver6)
Default(driver7)

