Help("""
       Type: 'scons' to build the production library,
             'scons -c' to clean the build,
             'scons debug=1' to build the debug version,
             'scons parallel=1' to build the parallel version (default).
       """)

import os
import multiprocessing

env = Environment(ENV=os.environ)

# Compiler Settings
CC_OPTS     = '-O0'
DEBUG_OPTS  = '-g -Wall'
CPP_COMP    = 'mpicxx'
C_COMP      = 'mpicc'

env['CXX'] = CPP_COMP
env['CC'] = C_COMP
#env.Append(CCFLAGS = DEBUG_OPTS) # for debugging - comment out if no debug

# Build Camellia Library
Export('env')
SConscript('../../SConscript')

# Build Driver
SConscript('SConscript')
