# include everything in this directory. 
camellia_dir = '../../build/mpi-debug'
includeDir = ['.','../DPGTests']

import os
# env = Environment(ENV=os.environ,CXX='mpicxx',CC='mpicc',CXXFLAGS = ['-O3','-w'],CPPPATH=includeDir)
env = Environment(ENV=os.environ,CXX='mpicxx',CC='mpicc',CXXFLAGS = ['-O0','-w'],CPPPATH=includeDir)
#env = Environment(ENV=os.environ,CXX='mpicxx',CC='mpicc',CXXFLAGS = ['-O0','-g'],CPPPATH=includeDir)

# run the Camellia library builder if it's not built already
Export('env', 'camellia_dir')
SConscript('../../SConscript')

# run current SCons script to build driver program
SConscript('SConscript')
