# include everything in this directory. 
includeDir = ['.']

#env = Environment(CXX='c++',CC='gcc',CXXFLAGS = '-O3',CPPPATH=includeDir)
import os
env = Environment(ENV=os.environ,CXX='mpicxx',CC='mpicc',CXXFLAGS = ['-O3','-w'],CPPPATH=includeDir)

#env = Environment(ENV=os.environ,CXX='/Users/jessechan/libs/openmpi-1.4.4/bin/mpicxx',CC='/Users/jessechan/libs/openmpi-1.4.4/bin/mpicc',CXXFLAGS = ['-O0','-g'],CPPPATH=includeDir)


# run the Camellia library builder if it's not built already
SConscript('../../build/SConscript',exports = 'env')

# run current SCons script to build driver program
SConscript('SConscript', exports=['env'])
