Import('*')

src_obj_confection = env.Object(['ConfusionBilinearForm.cpp','ConfectionManufacturedSolution.cpp','VortexManufacturedSolution.cpp','EricksonManufacturedSolution.cpp'])

src_obj = env.Object(['ConfusionBilinearForm.cpp','ConfusionManufacturedSolution.cpp','ConfusionProblem.cpp'])

env.Program('exec/AdaptiveConfusion',['AdaptiveConfusion.cpp',src_obj])

env.Program('exec/Confection',['ConfectionDriver.cpp',src_obj_confection])

env.Program('exec/Vortex',['VortexDriver.cpp',src_obj_confection])

env.Program('exec/Erickson',['EricksonDriver.cpp',src_obj_confection])
