# include everything in this directory. 
includeDir = Dir('.')
env = Environment(CXX='c++',CC='gcc',CXXFLAGS = '-O3',CPPPATH=includeDir)

# run the Camellia library builder if it's not built already
SConscript('../../build/SConscript',exports = 'env')

# run current SCons script to build driver program
SConscript('SConscript', exports=['env'])
