Import('*')

Poisson_dir = "../Poisson"
Poisson_files = Split("""
PoissonBCCubic.cpp
PoissonBCLinear.cpp
PoissonBCQuadratic.cpp
PoissonBCQuartic.cpp
PoissonBilinearForm.cpp
PoissonExactSolution.cpp
PoissonExactSolutionCubic.cpp
PoissonExactSolutionLinear.cpp
PoissonExactSolutionQuadratic.cpp
PoissonExactSolutionQuartic.cpp
PoissonRHSCubic.cpp
PoissonRHSLinear.cpp
PoissonRHSQuadratic.cpp
PoissonRHSQuartic.cpp
""")


for i in range(len(Poisson_files)):
    Poisson_files[i]=Poisson_dir+"/"+Poisson_files[i]

Confusion_dir = "../Confusion"
Confusion_files = Split("""
ConfusionBilinearForm.cpp
ConfusionProblem.cpp
ConfusionManufacturedSolution.cpp
""")

for i in range(len(Confusion_files)):
    Confusion_files[i]=Confusion_dir+"/"+Confusion_files[i]

# print Confusion_files    

src_obj = env.Object(['BasisCacheTests.cpp','FunctionTests.cpp','ScratchPadTests.cpp','LinearTermTests.cpp','TestBilinearFormDx.cpp','TestBilinearFormFlux.cpp','PatchBasisTests.cpp','VectorizedBasisTestSuite.cpp','MeshTestSuite.cpp','SolutionTests.cpp','RHSTests.cpp','MultiBasisTests.cpp','ElementTests.cpp','MeshRefinementTests.cpp',Poisson_files,Confusion_files,Glob('../MultiOrderStudy/*.cpp'),'../Stokes/StokesBilinearForm.cpp'])

env.Program('exec/DPGTests',['DPGTests.cpp',src_obj])
