Import('*')

files = Split("""
PoissonBilinearForm.cpp
PoissonExactSolution.cpp
../MultiOrderStudy/MultiOrderStudy.cpp 
""")

src_obj = env.Object(files)

#env.Program('exec/PoissonStudy',['PoissonStudy.cpp',src_obj])
env.Program('exec/PoissonExample',['PoissonExample.cpp',src_obj])
